<?php 
// create index keys for result array
$SUCCESS 				= "SUCCESS";
$MESSAGE				= "MESSAGE";
$DETAIL_MESSAGE			= "1_DETAIL_MESSAGE";
$PARTICIPANT			= "1_PARTICIPANT";
$MENTOR					= "1_MENTOR";

$HIDDEN_INPUTS_MISSING 	= "2_HIDDEN_INPUTS_MISSING";
$WRONG_NUM_FRIENDS		= "2_WRONG_NUM_FRIENDS";
$HONEYPOT_FILLED 		= "2_HONEYPOT_FILLED";
$WRONG_SIGNUP_TYPE 		= "2_WRONG_SIGNUP_TYPE";

$PARTICIPANT_EMAIL_USED	= "3_PARTICIPANT_EMAIL_USED";
$MENTOR_EMAIL_USED		= "3_MENTOR_EMAIL_USED";

$SELF_INPUTS_MISSING 	= "4_SELF_INPUTS_MISSING";
$SELF_INPUTS_EMPTY 		= "4_SELF_INPUTS_EMPTY";
$SELF_RECORD_ERROR		= "4_SELF_RECORD_ERROR";
$SELF_EMAIL_ERROR		= "4_SELF_EMAIL_ERROR";
$PARTICIPANT_SUCCESS	= "4_PARTICIPANT_SUCCESS";
$MENTOR_SUCCESS			= "4_MENTOR_SUCCESS";
$PARTICIPANT_KEY		= "4_PARTICIPANT_KEY";
$MENTOR_KEY				= "4_MENTOR_KEY";

$FILE_SIZE_TOO_LARGE	= "5_FILE_SIZE_TOO_LARGE";
$FILE_UPLOAD_ERROR		= "5_FILE_UPLOAD_ERROR";

$FRIENDS_TOTAL			= "6_FRIENDS_TOTAL";
$FRIEND_INPUTS_MISSING 	= "6_FRIENDS_INPUTS_MISSING";
$FRIEND_INPUTS_EMPTY 	= "6_FRIENDS_INPUTS_EMPTY";
$FRIEND_RECORD_ERROR	= "6_FRIENDS_SELF_RECORD_ERROR";
$FRIEND_EMAIL_ERROR		= "6_FRIENDS_SELF_EMAIL_ERROR";
$FRIEND_GEN_SUCCESS		= "6_FRIEND_GEN_SUCCESS";
$FRIEND_1_SUCCESS		= "6_FRIEND_1_SUCCESS";
$FRIEND_2_SUCCESS		= "6_FRIEND_2_SUCCESS";
$FRIEND_3_SUCCESS		= "6_FRIEND_3_SUCCESS";
$FRIEND_1_KEY			= "6_FRIEND_1_KEY";
$FRIEND_2_KEY			= "6_FRIEND_2_KEY";
$FRIEND_3_KEY			= "6_FRIEND_3_KEY";

$END_SUCCESS	= "100_END_SUCCESS";
?>